API change to improve VolumeGroupSnapshot restore
kubernetes-csi/external-snapshotter pull request #1068
Opened 2024-04-18 08:59 UTC by leonardoce

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
/kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

This PR implements an API change proposed by @xing-yang (see https://docs.google.com/document/d/1NdNwFD5Z64K2heQLYOnojt6Ogulg750BuYIJ6W9cEiM/edit?usp=sharing and the relative conversation in #969).

To ease the review process, this PR has been split into two commits:

1. a commit changing the API, including the generated files
2. some minimal changes on the controller and the CSI sidecar to allow the code to compile with the new API.

The information we have in `VolumeGroupSnapshot.status.volumeSnapshotRefList` has been moved into `VolumeGroupSnapshot.status.pvcVolumeSnapshotRefList.volumeSnapshotRef`.

The information we have in `VolumeGroupSnapshotContent.status.volumeSnapshotContentRefList` has been moved into `VolumeGroupSnapshotContent.status.volumeSnapshotContentRefList.volumeSnapshotContentName`.

The code to set the new fields has already been implemented, and I'm going to open a new PR based on this one.
I hope that it will be helpful for the reviewer.

If you prefer a single PR on multiple commits, just tell me.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

This is my first API-change PR. I followed the process described in `client/hack/README.md` as carefully as possible, but I encourage you to use special care when reviewing this.

**Testing**

After this patch, a `VolumeGroupSnapshot` will be defined as:

```
apiVersion: groupsnapshot.storage.k8s.io/v1alpha1
kind: VolumeGroupSnapshot
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"groupsnapshot.storage.k8s.io/v1alpha1","kind":"VolumeGroupSnapshot","metadata":{"annotations":{},"name":"new-groupsnapshot-demo","namespace":"default"},"spec":{"source":{"selector":{"matchLabels":{"cnpg.io/cluster":"cluster-example"}}},"volumeGroupSnapshotClassName":"csi-hostpath-groupsnapclass"}}
  creationTimestamp: "2024-04-18T08:46:09Z"
  finalizers:
  - groupsnapshot.storage.kubernetes.io/volumegroupsnapshot-bound-protection
  generation: 1
  name: new-groupsnapshot-demo
  namespace: default
  resourceVersion: "432302"
  uid: f01dec23-e263-41bb-9c94-dc7d73bb0e76
spec:
  source:
    selector:
      matchLabels:
        cnpg.io/cluster: cluster-example
  volumeGroupSnapshotClassName: csi-hostpath-groupsnapclass
status:
  boundVolumeGroupSnapshotContentName: groupsnapcontent-f01dec23-e263-41bb-9c94-dc7d73bb0e76
  creationTime: "2024-04-18T08:46:09Z"
  pvcVolumeSnapshotRefList:
  - persistentVolumeClaimRef: {}
    volumeSnapshotRef:
      kind: VolumeSnapshots
      name: snapshot-5b27c15878160c6941b056c305d4603fb62e3cacfea87b08b88ab38f1eb9932a-2024-04-18-8.46.11
      namespace: default
      uid: a875fa74-a790-4def-bf3b-a7d8c0ddde6b
  - persistentVolumeClaimRef: {}
    volumeSnapshotRef:
      kind: VolumeSnapshots
      name: snapshot-4140850f9fd1eba85a7577f378376c16e8f082ba3fd7355003112a2e19241b0b-2024-04-18-8.46.11
      namespace: default
      uid: 033e6190-6afc-47dd-a0ef-fc6368e17740
  readyToUse: true
```

And the corresponding VolumeGroupSnapshotContent would be like:

```
apiVersion: groupsnapshot.storage.k8s.io/v1alpha1
kind: VolumeGroupSnapshotContent
metadata:
  creationTimestamp: "2024-04-18T08:46:09Z"
  finalizers:
  - groupsnapshot.storage.kubernetes.io/volumegroupsnapshotcontent-bound-protection
  generation: 1
  name: groupsnapcontent-f01dec23-e263-41bb-9c94-dc7d73bb0e76
  resourceVersion: "432294"
  uid: 14321f38-d68d-4528-8252-8196c63762cc
spec:
  deletionPolicy: Delete
  driver: hostpath.csi.k8s.io
  source:
    volumeHandles:
    - 2aa5decf-fd5c-11ee-9872-1eeed5b8bdf2
    - 2aa6175f-fd5c-11ee-9872-1eeed5b8bdf2
  volumeGroupSnapshotClassName: csi-hostpath-groupsnapclass
  volumeGroupSnapshotRef:
    apiVersion: groupsnapshot.storage.k8s.io/v1alpha1
    kind: VolumeGroupSnapshot
    name: new-groupsnapshot-demo
    namespace: default
    resourceVersion: "432264"
    uid: f01dec23-e263-41bb-9c94-dc7d73bb0e76
status:
  creationTime: 1713429969692953103
  pvVolumeSnapshotContentRefList:
  - volumeSnapshotContentName: snapcontent-5b27c15878160c6941b056c305d4603fb62e3cacfea87b08b88ab38f1eb9932a-2024-04-18-8.46.11
  - volumeSnapshotContentName: snapcontent-4140850f9fd1eba85a7577f378376c16e8f082ba3fd7355003112a2e19241b0b-2024-04-18-8.46.11
  readyToUse: true
  volumeGroupSnapshotHandle: 1a6a54bf-fd60-11ee-a1b6-b678a7d4c7eb
```

**Does this PR introduce a user-facing change?**:

```release-note
Update API for group snapshots, easing the restore process.
```

2024-04-18 13:14 UTC, xing-yang commented
/assign

2024-04-18 13:14 UTC, xing-yang commented
/ok-to-test

2024-04-19 17:54 UTC, xing-yang commented on client/apis/volumegroupsnapshot/v1alpha1/types.go
> +	PVCVolumeSnapshotRefList []PVCVolumeSnapshotPair `json:"pvcVolumeSnapshotRefList,omitempty" protobuf:"bytes,6,opt,name=pvcVolumeSnapshotRefList"`
This should still be 5, not 6.

2024-04-19 17:54 UTC, xing-yang commented on client/apis/volumegroupsnapshot/v1alpha1/types.go
> +// PVCVolumeSnapshotPair defines a pair of a PVC reference and a Volume Snapshot
Volume Snapshot reference

2024-04-19 17:54 UTC, xing-yang commented on client/apis/volumegroupsnapshot/v1alpha1/types.go
> +	VolumeSnapshotRef core_v1.ObjectReference `json:"volumeSnapshotRef,omitempty" protobuf:"bytes,1,opt,name=volumeSnapshotRef"`
2

2024-04-19 17:54 UTC, xing-yang commented on client/apis/volumegroupsnapshot/v1alpha1/types.go
> +	// VolumeSnapshotCOntent for this group snapshot
PVVolumeSnapshotContentRefList -> PVVolumeSnapshotContentList
VolumeSnapshotCOntent -> VolumeSnapshotContent names

2024-04-19 17:54 UTC, xing-yang commented on client/apis/volumegroupsnapshot/v1alpha1/types.go
> +	PVVolumeSnapshotContentRefList []PVVolumeSnapshotContentPair `json:"pvVolumeSnapshotContentRefList,omitempty" protobuf:"bytes,6,opt,name=pvVolumeSnapshotContentRefList"`
PVVolumeSnapshotContentRefList -> PVVolumeSnapshotContentList

2024-04-19 17:54 UTC, xing-yang commented on client/apis/volumegroupsnapshot/v1alpha1/types.go
> +	VolumeSnapshotContentName string `json:"volumeSnapshotContentName,omitempty" protobuf:"bytes,1,opt,name=volumeSnapshotContentName"`
2

2024-04-20 08:10 UTC, leonardoce commented
Thank you @xing-yang for reviewing this. I should have taken care of your comments.

2024-04-22 14:19 UTC, xing-yang commented
/assign @bswartz

2024-04-22 16:42 UTC, bswartz requested changes
Actually after reviewing the change, I'm wondering why use object refs at all, if the PVC ref will always be a PVC and the snapshot ref will always be a VolumeSnapshot. Can't we do like the non-namespaced objects do and specify the object names, but omit their kinds? Namespace can be implied by the namespace of the containing object.

2024-04-22 16:42 UTC, bswartz commented on client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshots.yaml
> +                  pair that is part of this group snapshot. The maximum number of
pairs that are part

2024-04-22 16:42 UTC, bswartz commented on client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshots.yaml
> +                          description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
Kind must be PVC!

2024-04-22 16:42 UTC, bswartz commented on client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshots.yaml
> +                          description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
Kind must be VolumeSnapshot!

2024-04-22 16:47 UTC, xing-yang commented
> Actually after reviewing the change, I'm wondering why use object refs at all, if the PVC ref will always be a PVC and the snapshot ref will always be a VolumeSnapshot. Can't we do like the non-namespaced objects do and specify the object names, but omit their kinds? Namespace can be implied by the namespace of the containing object.

"Name" might be sufficient for now.  I'm wondering we may want to keep the namespace just in case in the future there's namespace transfer support.

2024-04-24 08:23 UTC, leonardoce commented
I replaced ObjectReferences with LocalObjectReferences and updated the code correspondingly. Thank you @bswartz @xing-yang

2024-04-24 19:45 UTC, xing-yang commented
LocalObjectReference looks good to me. We should probably use the same construct for PV and VolumeSnapshotContent pairs.
https://github.com/kubernetes/kubernetes/blob/v1.31.0-alpha.0/pkg/apis/core/types.go#L5460
cc @bswartz

2024-04-24 21:14 UTC, leonardoce commented
> LocalObjectReference looks good to me. We should probably use the same construct for PV and VolumeSnapshotContent pairs.

Nice. I changed the code for this and updated the example in the PR description.

2024-04-24 22:57 UTC, bswartz commented
> LocalObjectReference looks good to me. We should probably use the same construct for PV and VolumeSnapshotContent pairs. https://github.com/kubernetes/kubernetes/blob/v1.31.0-alpha.0/pkg/apis/core/types.go#L5460 cc @bswartz

Non-namespaced objects definitely should not be using namespaces. Assuming the kind is constant, why not just use an object name?

2024-04-26 15:11 UTC, xing-yang commented
>> LocalObjectReference looks good to me. We should probably use the same construct for PV and VolumeSnapshotContent pairs. https://github.com/kubernetes/kubernetes/blob/v1.31.0-alpha.0/pkg/apis/core/types.go#L5460 cc @bswartz

> Non-namespaced objects definitely should not be using namespaces. Assuming the kind is constant, why not just use an object name?

@msau42 From API design point of view,  are there pros and cons of using LocalObjectReference vs just a string here?

2024-05-02 00:20 UTC, bswartz approved these changes
/lgtm

2024-05-13 22:44 UTC, xing-yang commented
/lgtm
/approve

2024-05-13 23:37 UTC, merged