Add Helm Chart manifests and GitHub Release Helm Chart for the snapshot-controller component
kubernetes-csi/external-snapshotter pull request #622
Opened 2021-12-01 16:59 UTC by kaskol10

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

/kind design

**What this PR does / why we need it**:

The changes introduced with this PR allow for better integration snapshot-controller and Helm. Besides, publish the Helm Chart in the GitHub Releases Pages using a GitHub Action.

**Which issue(s) this PR fixes**:

Fixes [#551](https://github.com/kubernetes-csi/external-snapshotter/issues/551)

**Special notes for your reviewer**:
A GitHub branch called `gh-pages` would be needed to store the published charts. It's a pre-requisite for [chart-releaser-action](https://github.com/helm/chart-releaser-action#pre-requisites)
**Does this PR introduce a user-facing change?**:

```release-note
Added Helm Chart manifests and Helm Chart GitHub Release for snapshot-controller component
```

2021-12-01 17:02 UTC, kaskol10 commented
/assign @msau42

2021-12-14 18:43 UTC, z0rc commented
Please include [CRDs](https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crd) into chart as well.

2021-12-15 09:35 UTC, SamuelBagattin commented
> Please include [CRDs](https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crd) into chart as well.

According to [stevehipwell](https://github.com/stevehipwell), is it really a good practice to [install CRDs part of a helm chart](https://github.com/aws/containers-roadmap/issues/247#issuecomment-993351977) ?

2021-12-15 09:42 UTC, z0rc commented
@SamuelBagattin Helm isn't able to manage full lifecycle of CRDs, that's true, but it is quite capable of installing CRDs if there is none. Which solves initial deployment task. It's common practice on CRDs change to bump major chart version and provide instructions how to update CRDs, check out https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack.

2022-02-15 09:30 UTC, eumel8 commented
Great work, @kaskol10 , many thanks!
Any progress here on this PR? In the past we had our [own Helm chart for CRDs](https://github.com/mcsps/helm-charts/tree/master/charts/cinder-csi-snapshot-crds), before the snapshot controller manager was removed from [OpenStack Cinder CSI Chart](https://github.com/kubernetes/cloud-provider-openstack/pull/1705) and it's not available anymore since [openstack-cinder-csi-2.0.0](https://github.com/kubernetes/cloud-provider-openstack/releases/tag/openstack-cinder-csi-2.0.0). Would be a good idea to have a fast replacements, thx!

2022-04-14 11:15 UTC, SamuelBagattin commented
Hi @kaskol10 🙌
It's been a while there has been no more commit on this PR, and the helm chart would really help us 😊
Any update ?

2022-04-21 20:20 UTC, ggriffiths commented
/ok-to-test

2022-04-21 20:21 UTC, ggriffiths commented
My concern with this is continued support of helm charts by the maintainers, I am not sure if that's something the team would have the bandwidth to do for every release. I'll defer to @xing-yang as to if we want to continue maintaining helm charts for the snapshot-controller in this repo.

2022-04-21 23:18 UTC, xing-yang commented
> My concern with this is continued support of helm charts by the maintainers, I am not sure if that's something the team would have the bandwidth to do for every release. I'll defer to @xing-yang as to if we want to continue maintaining helm charts for the snapshot-controller in this repo.

Thanks @kaskol10 for your contribution.  As mentioned by @ggriffiths, that's exactly the concern we have.

2022-05-10 09:34 UTC, KlavsKlavsen commented
We too would really like an easy way to actually install this.. What other way do you recommend, instead of using a Helm Chart?

2022-05-10 17:01 UTC, ggriffiths commented
> We too would really like an easy way to actually install this.. What other way do you recommend, instead of using a Helm Chart?

The deployment files under [deploy/kubernetes](https://github.com/kubernetes-csi/external-snapshotter/tree/master/deploy/kubernetes) will work. We maintain those for every release with new flags/RBAC/etc.

If there's enough interest, maybe you can create a separate repo to house and maintain the Helm installation.

2022-05-13 17:38 UTC, sathieu commented
> My concern with this is continued support of helm charts by the maintainers,

Maybe the solution is to generate the plain manifests from the helm chart (and add a pipeline to ensure. WDYT?

NB: there is also [helmify](https://github.com/arttor/helmify/) to create charts from plain manifests.

2022-05-13 17:43 UTC, z0rc commented
Just FYI, there are helm charts already available at https://github.com/piraeusdatastore/helm-charts. It's perfectly fine, if projects maintainers don't want to support helm chart, helm community can help with existing chart maintained by 3rd party.

2022-08-30 05:47 UTC, kahirokunn commented
I need this helm.

2022-10-24 20:35 UTC, ggriffiths requested changes
Discussions on this feature request can happen here: https://github.com/kubernetes-csi/external-snapshotter/issues/551

Feel free to re-request a review for this PR if the request is approved or a maintainer is found

2022-12-20 20:07 UTC, iosifnicolae2 commented
When would be this PR reviewd?

Thank you!

2022-12-25 13:21 UTC, kahirokunn commented
I need this helm🥹

2023-03-25 15:12 UTC, sathieu commented
/remove-lifecycle stale

2023-06-23 19:55 UTC, kahirokunn commented
Keep

2023-08-30 20:16 UTC, Nuru commented
/remove-lifecycle stale

I would use a Helm chart if one were available.

2023-08-31 06:56 UTC, KlavsKlavsen commented
One maybe overlooked feature of using helm charts - is that they make it MUCH easier to automate monitoring for version updates, in a standardized way. We actually just have a script that looks through all our application helm charts (from upstream) - and talks to helm repo - to see if a new version exists..  Making it work pretty much like good old Linux repos - for k8s.

2023-08-31 13:56 UTC, z0rc commented
Everyone who still comments here. Have you seen https://github.com/piraeusdatastore/helm-charts/tree/main/charts/snapshot-controller? It was linked here at https://github.com/kubernetes-csi/external-snapshotter/pull/622#issuecomment-1126292632. Have you tried it? Is it missing something? There is already existing fully functional helm chart available.

2023-09-01 07:21 UTC, KlavsKlavsen commented
We are following the piraus charts - but IMHO its important that charts are "maintained alongside the code it installs" - as any other "release package". Thats the learnings from Helms "once upon a time - central package repository" - which was discontinues because things bitrot, when they don't live together. 
The install guide of this project SHOULD list the helm chart - and frankly I don't understand the hesitance to do so, when helm packages has such a huge advantage over "raw yaml" - for the users of the project (making k8s app maintenance much easier to do - as automation for monitoring for updates etc. . is made so much easier).

2023-09-01 09:02 UTC, z0rc commented
I don't buy it. History of "central package repository" doesn't have anything to do with this case. Instead Helm enables _anyone_ to package some manifests in a way they want to and distribute them. Project maintainers aren't obliged to provide a helm chart. This project isn't a unique case of not providing charts. Instead we see a raise of 3rd party repos that package multiple different projects (like https://github.com/bitnami/charts/tree/main/bitnami or https://github.com/deliveryhero/helm-charts/tree/master/stable), which is a good thing as this offloads burden from project maintainers and actually reduces chance of bitrot.

2023-09-01 11:12 UTC, KlavsKlavsen commented
No one said they were obliged. Its simply one of the best ways to consume k8s apps for the users, as it has features that enables easy monitoring for new versions f.ex. - instead of having to manually crawl through 50+ app repos (or how many you end up using), to check for updates regulary :)
If its a 3rd party, which true - some are - one has to be a bit more careful - and also watch out for "helm chart not being updated/following upstream anymore".

This is why f.ex. Ubuntu package a lot of applications into their repos - as Ubuntu users, then easily can follow updates and trust they're of decent quality and up2date.

With k8s there aren't really distros in the same way, so you follow the apps you choose to use - and Helm really makes that easier, and also allows for applications to "simplify" install options, via the templating and values features of Helm.

We're using it in our open source project https://github.com/Obmondo/k8id/tree/master/argocd-helm-charts/external-snapshotter - to f.ex. allow specifying multiple helm charts that needs to be installed to have a working external-snapshotter setup - trying to make everyones life easier, operating k8s :)

2024-03-11 00:52 UTC, kahirokunn commented
/remove-lifecycle stale

2024-07-09 03:42 UTC, Nuru commented
/remove-lifecycle rotten

I'd still like to see this and would use it if it were available

2024-12-04 23:05 UTC, pschichtel commented
/remove-lifecycle stale

2025-01-05 00:38 UTC, M0NsTeRRR commented
I recently encountered an issue where I updated the file `https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v8.2.0/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml` in my `kustomization.yaml` to the new tag `v8.2.0`. However, it turned out that it was using the wrong image (`registry.k8s.io/sig-storage/snapshot-controller:v8.0.1`). This issue was fixed in a later commit, but that fix is not included in the `v8.2.0` tag. 

The root cause seems to be that, when a new tag is released, there are many files to update (e.g., deployments, CRDs, etc.), which increases the chances of such issues occurring. In contrast, Helm charts only require bumping the `appVersion`, which helps to avoid this kind of problem.

I understand your concern about maintaining the Helm chart, but given how widely used this project is, I really don't think that neglecting maintenance will become an issue.

2025-04-07 12:50 UTC, druchoo commented
/remove-lifecycle stale

2025-04-07 18:01 UTC, haiwu commented
any luck to move forward with this?

2025-07-09 12:37 UTC, druchoo commented
/remove-lifecycle stale

2025-12-03 20:45 UTC, druchoo commented
/remove-lifecycle rotten

2026-03-03 21:30 UTC, frittentheke commented
/remove-lifecycle stale

2026-07-31 23:30 UTC, closed without merging