lift the dependencies and correct format errors based on 1.19
kubernetes-csi/external-snapshotter pull request #758
Opened 2022-09-06 09:44 UTC by humblec

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

> /kind cleanup

```release-note
NONE
```

2022-09-06 15:05 UTC, pohly commented on go.mod
> +go 1.19
Why this version bump?

It causes the unit test to fail (still runs with Go 1.18, which doesn't support `go 1.19`) and shouldn't be necessary (go 1.19 can compile code that only depends on features from `go 1.17`).

2022-09-06 18:34 UTC, xing-yang commented
Please don't update anything in the client folder yet.
/hold

2022-09-07 04:05 UTC, humblec commented on vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumesnapshot/v1/types.go
> +//   - Fields in VolumeSnapshotContentStatus can be used for filtering when importing a
I was referrring the update in client go.mod with version bump to kube v1.25 https://github.com/kubernetes-csi/external-snapshotter/pull/758/files#diff-de2c00fe7d49a7bb4d5c225eded980780a7b9dde4ae89e70c7e497cd0e45b15bL9-R6 by lift the dependencies.

2022-09-07 05:44 UTC, pohly commented
IMHO all that this PR should do is make the formatting compliant with Go 1.19 and nothing else. Then we can merge https://github.com/kubernetes-csi/csi-release-tools/pull/203.

2022-09-07 05:55 UTC, humblec commented
> IMHO all that this PR should do is make the formatting compliant with Go 1.19 and nothing else. Then we can merge [kubernetes-csi/csi-release-tools#203](https://github.com/kubernetes-csi/csi-release-tools/pull/203).

ok.. let me shrink the PR to just do formatting based on 1.19 in that case.

2022-09-07 06:08 UTC, humblec commented
@pohly @xing-yang as per the above discussion, I have kept only formatting change here in this PR. ptal.. Thanks..

2022-09-07 08:06 UTC, pohly requested changes

2022-09-07 08:06 UTC, pohly commented on pkg/common-controller/snapshot_controller.go
> +//	snapshot - snapshot to update
I think a bullet list is more appropriate here.

2022-09-07 08:06 UTC, pohly commented on pkg/sidecar-controller/snapshot_controller.go
> +//	content - content to update
And here.

2022-09-07 13:39 UTC, xing-yang commented
/hold cancel

2022-09-13 07:28 UTC, humblec commented on pkg/sidecar-controller/snapshot_controller.go
> +//	content - content to update
done @pohly .. ptal.. thanks.

2022-09-13 07:53 UTC, pohly commented
Can you remove the dependency update commit? It is unrelated to this PR.

2022-09-13 07:56 UTC, pohly commented
You probably added it because of a Trivy failure, but that's just bad style. I'm really getting annoyed by this security check.

2022-09-13 07:57 UTC, humblec commented
> Can you remove the dependency update commit? It is unrelated to this PR.

The  Trivvy  scnner fail here in this PR on lastest run, so clubbed with the same. I can split that to another PR too and mark it as dependency for this PR. 
@pohly  wdyt?

2022-09-13 07:58 UTC, humblec commented
> You probably added it because of a Trivy failure, but that's just bad style. I'm really getting annoyed by this security check.

Indeed . Thats why I refreshed with that change. Let me split that up first.

2022-09-13 08:03 UTC, humblec commented
The trrivvy failure is addressed here https://github.com/kubernetes-csi/external-snapshotter/pull/759

2022-09-13 14:08 UTC, humblec commented
> The trrivvy failure has been addressed here #759

As the trivvy failure has been addressed on master, I have rebased this PR.  This should be good to go as well @xing-yang @pohly

2022-09-13 14:51 UTC, pohly approved these changes
/lgtm

2022-09-13 15:42 UTC, xing-yang commented
/lgtm
/approve

2022-09-13 15:43 UTC, merged